site_name: SyncrnzdClk's Notebook
site_author: SyncrnzdClk
theme:
  name: material
  features:
    - navigation.instant
nav:
  - HomePage: index.md
  - abstract_algebra: 
    - pre: abstract_algebra/pre.md
    - notes: 
      - preliminaries and integers: abstract_algebra\notes\preliminaries.md
      - groups: abstract_algebra\notes\groups.md
      - cyclic groups: abstract_algebra\notes\cyclic groups.md
  - convex optimization: 
    - pre: convex optimization/pre.md
    - notes: 
      - convex sets and functions: convex optimization/notes/convex sets and functions.md
      - convex optimization basics: convex optimization/notes/convex optimization basics.md
      - gradiant descent: convex optimization/notes/gradient descent.md
  - probability:
    - pre: probability/pre.md
    - notes:
      - probability space: probability/probability space.md
  - statistical learning:
    - pre: statistical learning/pre.md
    - notes:
      - perceptron: statistical learning/perceptron.md
      - kNN: statistical learning/kNN.md
      - decision tree: statistical learning/decision tree.md
      - logistic regression: statistical learning/logistic regression.md
  - computer vision:
    - pre: computer vision/pre.md
    - notes: 
      - graphics: computer vision/notes/graphics.md
  - ads:
    - pre: ads/pre.md
    - notes: 
      - leftist heap and skew heap: ads/notes/leftist heap and skew heap.md
  - computer architecture:
    - pre: computer architecture/pre.md
    - notes:
      - float: computer architecture/notes/float.md
  - environment:
    - various kinds of problems: environment/various kinds of problems.md 
markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css